# docker run -d -p 6379:6379 -i -t redis:3.2.5-alpine

version: '3'
services:
    redis:
        image: redis:3.2.5-alpine
        restart: always
        ports:
            - '6379:6379'
        
    api:
        image: jwt-project-core/api:latest
        build: ./
        restart: always
        environment:
            - REDIS_HOST=redis:6379
        ports:
            - '5000:80'

            